/**
 * Registre des traitements (art. 30 RGPD) — auto-seedé au démarrage.
 * 8 traitements types pour un organisme RH multi-entités.
 */
export const SEED_ACTIVITIES = [
  {
    name: 'Gestion administrative du personnel',
    purpose: 'Tenue des dossiers salariés, suivi des contrats et des évolutions de poste, gestion des absences et congés.',
    legalBasis: 'contrat',
    dataCategories: ['Identité', 'Coordonnées', 'Famille', 'NIR', 'Coordonnées bancaires', 'Carrière', 'Salaire'],
    dataSubjects: ['Salariés'],
    recipients: ['Service RH', 'Manager direct', 'URSSAF', 'Inspection du travail (sur demande)'],
    retentionPeriod: '5 ans après fin du contrat de travail (durée de prescription)',
    securityMeasures: 'Chiffrement at-rest des données sensibles (NIR, IBAN, salaire), authentification 2FA pour les accès RH, audit log complet.',
    transfersOutsideEU: false,
  },
  {
    name: 'Gestion de la paie',
    purpose: 'Calcul et édition des bulletins de paie, déclarations sociales (DSN), versement des salaires.',
    legalBasis: 'obligation_legale',
    dataCategories: ['Identité', 'NIR', 'Coordonnées bancaires', 'Composantes du salaire', 'Absences'],
    dataSubjects: ['Salariés'],
    recipients: ['Service Paie', 'URSSAF', 'DGFiP', 'Caisses de retraite', 'Mutuelle santé', 'Prévoyance'],
    retentionPeriod: 'Bulletins de paie : 50 ans (jusqu\'à la liquidation des droits à retraite). Comptabilité : 10 ans.',
    securityMeasures: 'Chiffrement at-rest, accès restreint aux gestionnaires de paie, audit log.',
    transfersOutsideEU: false,
  },
  {
    name: 'Recrutement',
    purpose: 'Sélection des candidats, gestion des entretiens et des candidatures.',
    legalBasis: 'consentement',
    dataCategories: ['Identité', 'Coordonnées', 'CV', 'Diplômes', 'Expérience professionnelle'],
    dataSubjects: ['Candidats'],
    recipients: ['Service RH', 'Manager du poste'],
    retentionPeriod: 'Candidatures non retenues : 2 ans après le dernier contact (recommandation CNIL). Candidatures retenues : intégrées au dossier salarié.',
    securityMeasures: 'Accès restreint, suppression automatique à 2 ans.',
    transfersOutsideEU: false,
  },
  {
    name: 'Gestion des temps et activités',
    purpose: 'Suivi des heures travaillées, des congés, des absences et des heures supplémentaires.',
    legalBasis: 'contrat',
    dataCategories: ['Identité', 'Horaires de travail', 'Absences', 'Motifs d\'absence'],
    dataSubjects: ['Salariés'],
    recipients: ['Manager direct', 'Service RH', 'Service Paie'],
    retentionPeriod: '5 ans (durée de prescription du Code du travail)',
    securityMeasures: 'Audit log, accès restreint.',
    transfersOutsideEU: false,
  },
  {
    name: 'Formation professionnelle',
    purpose: 'Suivi du plan de formation, des compétences et des entretiens professionnels.',
    legalBasis: 'obligation_legale',
    dataCategories: ['Identité', 'Diplômes', 'Compétences', 'Formations suivies', 'Évaluations'],
    dataSubjects: ['Salariés'],
    recipients: ['Service RH', 'OPCO', 'Organismes de formation'],
    retentionPeriod: '6 ans (durée de la consultation des IRP)',
    securityMeasures: 'Accès restreint.',
    transfersOutsideEU: false,
  },
  {
    name: 'Visite médicale et santé au travail',
    purpose: 'Suivi médical réglementaire des salariés.',
    legalBasis: 'obligation_legale',
    dataCategories: ['Identité', 'Coordonnées', 'Convocations'],
    dataSubjects: ['Salariés'],
    recipients: ['Service de santé au travail (SST)'],
    retentionPeriod: '5 ans après fin du contrat',
    securityMeasures: 'Aucune donnée médicale ne transite par le SIRH — uniquement les dates de visite.',
    transfersOutsideEU: false,
  },
  {
    name: 'Vidéosurveillance / Badges d\'accès',
    purpose: 'Sécurité des locaux et contrôle des accès.',
    legalBasis: 'interet_legitime',
    dataCategories: ['Identité', 'Horaires d\'accès', 'Photo (badge)'],
    dataSubjects: ['Salariés', 'Visiteurs'],
    recipients: ['Service sécurité'],
    retentionPeriod: 'Vidéos : 1 mois. Logs d\'accès : 3 mois.',
    securityMeasures: 'Accès restreint, suppression automatique.',
    transfersOutsideEU: false,
  },
  {
    name: 'Notifications et communication interne',
    purpose: 'Envoi d\'emails RH, notifications, courriers.',
    legalBasis: 'contrat',
    dataCategories: ['Identité', 'Email professionnel'],
    dataSubjects: ['Salariés'],
    recipients: ['Service RH'],
    retentionPeriod: 'Durée du contrat de travail',
    securityMeasures: 'Audit log.',
    transfersOutsideEU: false,
  },
];
